---

- name: 'install the openntpd config file'
  template:
    src: 'etc/openntpd/ntpd.conf.j2'
    dest: "{{ _openntpd_conf_dir }}/ntpd.conf"
    owner: 'root'
    group: "{{ _openntpd_root_group }}"
    mode: '0644'
    # validate: "{{ openntpd_bin_path }} -f %s -n"
  notify:
    - 'openntpd_restart_handler'
