---

- name: gather data about services
  service_facts:

- name: disable ntp services
  service:
    name: "{{ item.name }}"
    state: stopped
    enabled: False
  when: >
    ansible_facts['services'][item.name + '.service'] is defined
  loop: "{{ openntpd_ntpd_to_remove }}"

- name: mask ntp services
  systemd:
    name: "{{ item.name }}"
    masked: True
  when: >
    ansible_facts['service_mgr'] == 'systemd'
    and ansible_facts['services'][item.name + '.service'] is defined
  loop: "{{ openntpd_ntpd_to_remove }}"

- include_role:
    name: t18s.fr_pkg
  vars:
    pkg_list: "{{ openntpd_ntpd_to_remove | json_query(\"[*].packages | [].{ name: name, state: 'absent' }\") }}"
