---

- name: 'Converge'
  hosts: 'all'
  become: True

  roles:
    - role: 'ansible-role-openntpd'
      openntpd_pools:
        - type: servers
          address: 0.debian.pool.ntp.org

        - type: servers
          address: 1.debian.pool.ntp.org
